version: '3'
volumes: 
    dados:
services: 
    db:
        image: postgres:9.6
        environment:
            POSTGRES_DB: "docker"
            POSTGRES_USER: "docker"
            POSTGRES_PASSWORD: "password"
        ports: 
             - 5432:5432
        volumes:
            # Volume dos dados 
            - dados:/var/lib/postgresql/data
            # Scripts
            #- ./scripts:/scripts
            - ./src/database/init.sql:/docker-entrypoint-initdb.d/init.sql
            - ./src/database/check.sql:/check.sql
